### ISSUE TITLE
File isn't opened to cursor position

### ISSUE THREAD

**Issue by maverick1872** [Almo7aya/openingh.nvim#16]
Suggestions on what to investigate would be appreciated.

**Comment by vitarb** [comment]
I've found work-around, this feature seems to work well in visual mode, but in normal mode line number is ignored.

**Comment by Almo7aya** [comment]
Funny enough this was a feature but it got removed as @PlaiyTiziano suggested here https://github.com/Almo7aya/openingh.nvim/pull/13

What do you think guys should we add a new command to only open the file, and make the old one respect the cursor position?

**Comment by vitarb** [comment]
I think it would make sense to have 2 commands, one that just opens a file, and the other one that opens specific line number.

**Comment by Almo7aya** [comment]
What do you think about this ? 
https://github.com/Almo7aya/openingh.nvim/pull/18

**Comment by Almo7aya** [comment]
What do you think about this ? 
https://github.com/Almo7aya/openingh.nvim/pull/18

**Comment by vitarb** [comment]
I think it's a good one as long as default behavior is to open current line where the cursor is.

**Comment by maverick1872** [comment]
Left my thoughts on the PR. Personally, I'm good with whatever now that I'm aware it functions in visual mode.
