### ISSUE TITLE
How to change https to http?

### ISSUE THREAD

**Issue by TBBtianbaoboy** [Almo7aya/openingh.nvim#5]
For instance, I want to open a gitlab repo with HTTP, but this plugin default use https?

**Comment by Almo7aya** [comment]
Umm, I'll look into that, probably caused by this line https://github.com/Almo7aya/openingh.nvim/blob/main/lua/openingh/utils.lua#L24

**Comment by Almo7aya** [comment]
@TBBtianbaoboy can u test this PR's branch https://github.com/Almo7aya/openingh.nvim/pull/6 

`chore/handle_http_remote_urls`
